version: '3.1'

services:
    web:
        image: nginx:latest
        ports:
            - "8888:80"
        volumes:
            - ./:/code
            - ./config/site.conf:/etc/nginx/conf.d/default.conf

    php:
        image: chialab/php:7.2-fpm
        volumes:
            - ./:/code

    db:
        image: mariadb
        environment:
            MYSQL_DATABASE: nevnap_api
            MYSQL_USER: nevnap
            MYSQL_PASSWORD: nevnap
            MYSQL_ROOT_PASSWORD: nevnap